# This file is intentionally left blank for now. 

version: '3.8'

services:
  gateway:
    build: ./services/gateway
    ports:
      - "8000:8000"
    environment:
      - FEEDBACK_SERVICE_URL=http://feedback-service:8001
      - MEMBER_SERVICE_URL=http://member-service:8002
    depends_on:
      - feedback-service
      - member-service

  feedback-service:
    build: ./services/feedback-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/feedback_db
    depends_on:
      - db

  member-service:
    build: ./services/member-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/member_db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feedback_db # This will create one DB, member_db needs to be created manually or via init script
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/create-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh
    ports:
      - "5432:5432"

volumes:
  postgres_data: 